spring:
  # DB??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:filterdb
    username: sa
    password:

  # JPA
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
      dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_KEY}
            client-secret: ${GOOGLE_PWD}
            scope: email, profile

          naver:
            client-id: ${NAVER_KEY}
            client-secret: ${NAVER_PWD}
            redirect-uri: http://localhost:8080/auth/oauth/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email

          kakao:
            client-id: ${KAKAO_KEY}
            redirect-uri: http://localhost:8080/auth/oauth/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    key: ${JWT_SECRET_KEY}
    live:
      atk: 300000
      rtk: 3000000

server:
  port: 8080